services:

  waf:
    image: haproxy:lts-alpine
    volumes:
      - ./waf:/usr/local/etc/haproxy:ro
    ports:
      - 8100:8080
      - 8150:9090
    depends_on:
      web:
        condition: service_started

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8200:80
    depends_on:
      tier1:
        condition: service_started

  tier1:
    build:
      context: ./tier1
      dockerfile: Dockerfile
    ports:
      - 8300:8080
    depends_on:
      tier2:
        condition: service_started
      queue:
        condition: service_healthy

  tier2:
    build:
      context: ./tier2
      dockerfile: Dockerfile
    ports:
      - 8400:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 8500:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 12

  queue:
    image: rabbitmq:3-management
    ports:
      - 8600:15672
      - 8650:5672
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics" ,"-q", "ping"]
      timeout: 10s
      retries: 12

  queue_consumer:
    build:
      context: ./cons
      dockerfile: Dockerfile
    ports:
      - 8700:80
    depends_on:
      queue:
        condition: service_healthy
      db:
        condition: service_healthy
